/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ouc.cpss.view;

import com.ouc.cpss.po.User;
import com.ouc.cpss.util.FrameUtil;
import com.ouc.cpss.util.LocationUtil;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import com.ouc.cpss.biz.UserBiz;
import com.ouc.cpss.biz.UserBizImpl;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class MainFrame extends javax.swing.JFrame {

    public static User user;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        LocationUtil.setFullScreen(this);
        this.btnLogin.setEnabled(false);
        //标题栏显示用户登录信息
        this.setTitle(user.getUsname() + "-" + user.getPosition());
        //权限
        if (user.getPosition().equals("销售员")) {
            this.menuBasic.setEnabled(false);
            this.menuPurchase.setEnabled(false);
            this.menuCount.setEnabled(false);
            this.btnCustomer.setEnabled(false);
            this.btnEmployee.setEnabled(false);
            this.btnProduct.setEnabled(false);
            this.btnSupplier.setEnabled(false);
        } else if (user.getPosition().equals("基本资料管理员")) {
            this.menuSell.setEnabled(false);
            this.menuPurchase.setEnabled(false);
            this.menuCount.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProduct = new javax.swing.JButton();
        btnSupplier = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        mainDeskPane2 = new com.ouc.cpss.view.MainDeskPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBasic = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuPurchase = new javax.swing.JMenu();
        itemPurIn = new javax.swing.JMenuItem();
        itemPurReturn = new javax.swing.JMenuItem();
        itemPurQuery = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menuSell = new javax.swing.JMenu();
        itemSelout = new javax.swing.JMenuItem();
        itemSelrt = new javax.swing.JMenuItem();
        itemSelQuery = new javax.swing.JMenuItem();
        itemSelrtInfo = new javax.swing.JMenuItem();
        menuCount = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/cpss/img/product.gif"))); // NOI18N
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductActionPerformed(evt);
            }
        });

        btnSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/cpss/img/supplier.gif"))); // NOI18N
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierActionPerformed(evt);
            }
        });

        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/cpss/img/customer.gif"))); // NOI18N
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        btnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/cpss/img/salesman.gif"))); // NOI18N
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });

        btnLogin.setText("登录");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnRegister.setText("注册");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnLogout.setText("注销");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        menuBasic.setText("基本资料管理");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/cpss/img/productmnu.gif"))); // NOI18N
        jMenuItem1.setText("商品管理");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuBasic.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/cpss/img/salesmanmnu.gif"))); // NOI18N
        jMenuItem2.setText("员工管理");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuBasic.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/cpss/img/customermnu.gif"))); // NOI18N
        jMenuItem3.setText("买家管理");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuBasic.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/cpss/img/suppliernum.gif"))); // NOI18N
        jMenuItem4.setText("供应商管理");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuBasic.add(jMenuItem4);

        jMenuBar1.add(menuBasic);

        menuPurchase.setText("采购管理");

        itemPurIn.setText("采购入库");
        itemPurIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPurInActionPerformed(evt);
            }
        });
        menuPurchase.add(itemPurIn);

        itemPurReturn.setText("采购退货");
        itemPurReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPurReturnActionPerformed(evt);
            }
        });
        menuPurchase.add(itemPurReturn);

        itemPurQuery.setText("采购查询");
        itemPurQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPurQueryActionPerformed(evt);
            }
        });
        menuPurchase.add(itemPurQuery);

        jMenuItem5.setText("退货查询");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuPurchase.add(jMenuItem5);

        jMenuBar1.add(menuPurchase);

        menuSell.setText("销售管理");

        itemSelout.setText("销售出库");
        itemSelout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSeloutActionPerformed(evt);
            }
        });
        menuSell.add(itemSelout);

        itemSelrt.setText("销售退货");
        itemSelrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSelrtActionPerformed(evt);
            }
        });
        menuSell.add(itemSelrt);

        itemSelQuery.setText("销售查询");
        itemSelQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSelQueryActionPerformed(evt);
            }
        });
        menuSell.add(itemSelQuery);

        itemSelrtInfo.setText("退货查询");
        itemSelrtInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSelrtInfoActionPerformed(evt);
            }
        });
        menuSell.add(itemSelrtInfo);

        jMenuBar1.add(menuSell);

        menuCount.setText("统计管理");

        jMenuItem11.setText("供应商交易记录");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        menuCount.add(jMenuItem11);

        jMenuItem12.setText("买家交易记录");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        menuCount.add(jMenuItem12);

        jMenuItem13.setText("商品库存查询");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        menuCount.add(jMenuItem13);

        jMenuItem14.setText("商品销售Top10");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        menuCount.add(jMenuItem14);

        jMenuItem15.setText("销售员每月销售总额统计");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        menuCount.add(jMenuItem15);

        jMenuItem16.setText("销售员销售商品明细");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        menuCount.add(jMenuItem16);

        jMenuItem17.setText("每月总利润");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        menuCount.add(jMenuItem17);

        jMenuBar1.add(menuCount);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSupplier)
                    .addComponent(btnCustomer)
                    .addComponent(btnProduct)
                    .addComponent(btnEmployee)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegister)
                            .addComponent(btnLogout)
                            .addComponent(btnLogin))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainDeskPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnLogin)
                .addGap(18, 18, 18)
                .addComponent(btnRegister)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addGap(34, 34, 34)
                .addComponent(btnProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnEmployee)
                .addGap(29, 29, 29)
                .addComponent(btnCustomer)
                .addGap(27, 27, 27)
                .addComponent(btnSupplier)
                .addContainerGap(136, Short.MAX_VALUE))
            .addComponent(mainDeskPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemPurInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPurInActionPerformed
        showFrame(PurInFrame.class);
    }//GEN-LAST:event_itemPurInActionPerformed

    private void itemPurReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPurReturnActionPerformed
        showFrame(PurReturnFrame.class);
    }//GEN-LAST:event_itemPurReturnActionPerformed

    private void itemPurQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPurQueryActionPerformed
        showFrame(PurInfoFrame.class);
    }//GEN-LAST:event_itemPurQueryActionPerformed

    private void itemSelQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSelQueryActionPerformed
        showFrame(SelInfoFrame.class);
    }//GEN-LAST:event_itemSelQueryActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // 登录
        this.dispose();
        LoginFrame lf = new LoginFrame();
        lf.setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void itemSelrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSelrtActionPerformed
        showFrame(SelReturnFrame.class);
    }//GEN-LAST:event_itemSelrtActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        showFrame(PurReturnInfoFrame.class);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void itemSelrtInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSelrtInfoActionPerformed
        showFrame(SelReturnInfoFrame.class);
    }//GEN-LAST:event_itemSelrtInfoActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // 注销
        JOptionPane.showMessageDialog(this, "注销成功！");
        this.menuBasic.setEnabled(false);
        this.menuSell.setEnabled(false);
        this.menuPurchase.setEnabled(false);
        this.menuCount.setEnabled(false);
        this.btnCustomer.setEnabled(false);
        this.btnEmployee.setEnabled(false);
        this.btnProduct.setEnabled(false);
        this.btnSupplier.setEnabled(false);
        this.btnLogin.setEnabled(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void itemSeloutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSeloutActionPerformed
        showFrame(SelOutFrame.class);
    }//GEN-LAST:event_itemSeloutActionPerformed

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        showFrame(ProductFrame.class);
    }//GEN-LAST:event_btnProductActionPerformed

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
        showFrame(EmployeeFrame.class);
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        showFrame(CustomerFrame.class);
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
        showFrame(SupplierFrame.class);
    }//GEN-LAST:event_btnSupplierActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        showFrame(ProductFrame.class);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        showFrame(EmployeeFrame.class);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        showFrame(CustomerFrame.class);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        showFrame(SupplierFrame.class);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        showFrame(EmpSaleFrame.class);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        showFrame(ProfitFrame.class);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        showFrame(CusTradeFrame.class);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        showFrame(SupTradeFrame.class);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        showFrame(StorecountFrame.class);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        showFrame(EmpSelProFrame.class);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        showFrame(ProTop10Frame.class);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    public void showFrame(Class clazz) {
        try {
            // new 对象
            JInternalFrame frame = FrameUtil.buildFrame(clazz);
            // 桌面容器先删除
            this.mainDeskPane2.remove(frame);
            // 桌面容器再添加
            this.mainDeskPane2.add(frame);
            // 显示
            LocationUtil.setScreenCenter(frame);
            frame.setVisible(true);
            // 显示在最前
            frame.toFront();
            // 处于选中状态
            frame.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JMenuItem itemPurIn;
    private javax.swing.JMenuItem itemPurQuery;
    private javax.swing.JMenuItem itemPurReturn;
    private javax.swing.JMenuItem itemSelQuery;
    private javax.swing.JMenuItem itemSelout;
    private javax.swing.JMenuItem itemSelrt;
    private javax.swing.JMenuItem itemSelrtInfo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private com.ouc.cpss.view.MainDeskPane mainDeskPane2;
    private javax.swing.JMenu menuBasic;
    private javax.swing.JMenu menuCount;
    private javax.swing.JMenu menuPurchase;
    private javax.swing.JMenu menuSell;
    // End of variables declaration//GEN-END:variables
}
