/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ouc.cpss.view;

import com.ouc.cpss.biz.ProductBiz;
import com.ouc.cpss.biz.ProductBizImpl;
import com.ouc.cpss.biz.PurchaseBiz;
import com.ouc.cpss.biz.PurchaseBizImpl;
import com.ouc.cpss.biz.SupplierBiz;
import com.ouc.cpss.biz.SupplierBizImpl;
import com.ouc.cpss.po.Product;
import com.ouc.cpss.po.Supplier;
import com.ouc.cpss.util.FrameUtil;
import com.ouc.cpss.util.StringUtil;
import java.math.BigDecimal;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author su
 */
public class PurInFrame extends javax.swing.JInternalFrame {

    ProductBiz pbiz = new ProductBizImpl();
    PurchaseBiz purbiz = new PurchaseBizImpl();
    SupplierBiz supbiz = new SupplierBizImpl();
    // 为了点删除时有选中行
    int selectedRow = -1;

    /**
     * Creates new form PurInFrame
     */
    public PurInFrame() {
        initComponents();
        initPurchaseTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCondition = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPurchase = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnPurIn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("采购入库");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        btnSearch.setText("查询");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "商品编号", "商品名称", "商品型号", "商品颜色", "商品单价", "安全存量", "当前数量"
            }
        ));
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduct);

        tblPurchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "商品编号", "商品名称", "商品型号", "供应商", "采购数量", "采购单价", "采购总金额"
            }
        ));
        tblPurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPurchaseMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPurchase);

        jLabel1.setText("加入采购");

        btnDelete.setText("删除");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnPurIn.setText("采购入库");
        btnPurIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnPurIn)
                                .addGap(36, 36, 36)
                                .addComponent(btnDelete))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearch)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnPurIn))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
        // 将选中的商品添加到采购表中
        int selectrow = this.tblProduct.getSelectedRow();
        Integer pid = (Integer) this.tblProduct.getValueAt(selectrow, 0);
        String pname = (String) this.tblProduct.getValueAt(selectrow, 1);
        String ptype = (String) this.tblProduct.getValueAt(selectrow, 2);

        Vector vt = new Vector();
        vt.add(pid); // vt.get(0)
        vt.add(pname);
        vt.add(ptype);
        //添加到采购表格
        addPurchaseTable(vt);
    }//GEN-LAST:event_tblProductMouseClicked


    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        //1 获得条件
        String condition = this.txtCondition.getText().trim();
        //2 通过查询业务获得商品集合
        List<Product> list = pbiz.findByCondition(condition);
        //3 显示在表格
        showOnProductTable(list);

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "请选择要删除的采购信息");
            return;
        }
        //tblPurchase :采购信息表变量名
        DefaultTableModel dtm = (DefaultTableModel) this.tblPurchase.getModel();
        dtm.removeRow(selectedRow);
        selectedRow = -1; //还原选择行号

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnPurInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurInActionPerformed
        //加入采购 按钮                                      
        //获取信息
        DefaultTableModel dtm = (DefaultTableModel) this.tblPurchase.getModel();
        //行根据表格中的数据行，列根据sql语句中的参数
        Object[][] purchase = new Object[dtm.getRowCount()][6];//根据具体数值数创建采购数组
        Object[][] stocks = new Object[dtm.getRowCount()][2];//商品库存数组
        //遍历表格
        for (int i = 0; i < dtm.getRowCount(); i++) {
            //采购表
            //purid,proid,supid,purdate,purcount,purprice,purtotal,state) values(?,?,?,?,?,?,?,1)
            //getValueAt(i, 4)中的4指窗体采购表中的第4列
            purchase[i][0] = null;
            purchase[i][1] = this.tblPurchase.getValueAt(i, 0);//商品编号
            Supplier sup = (Supplier) this.tblPurchase.getValueAt(i, 3);
            purchase[i][2] = sup.getSupid();//供应商id
            purchase[i][3] = new java.util.Date();

            String count_s = (String) this.tblPurchase.getValueAt(i, 4);
            if (StringUtil.checkDigit(count_s)) {
                purchase[i][4] = new Integer(count_s); //采购数量
            } else {
                JOptionPane.showMessageDialog(this, "数量必须为数字！");
                return;
            }

            //采购价格（验证）
            String price_s = (String) this.tblPurchase.getValueAt(i, 5);
            if (StringUtil.checkDecimal(price_s)) {
                purchase[i][5] = new BigDecimal(price_s);//采购价格
            } else {
                JOptionPane.showMessageDialog(this, "价格必须为数字！");
                return;
            }

            //总金额，价格 * 数量
            //purchase[i][6] = new BigDecimal(purchase[i][4].toString()).multiply(new BigDecimal(purchase[i][5].toString()));
            this.tblPurchase.setValueAt(new BigDecimal(purchase[i][4].toString()).multiply(new BigDecimal(purchase[i][5].toString())), i, 6);

            stocks[i][0] = this.tblPurchase.getValueAt(i, 4);  //采购数量
            stocks[i][1] = this.tblPurchase.getValueAt(i, 0); //商品编号

        }
        //调用批量添加
        boolean result = purbiz.purchasein(purchase, stocks);
        if (result == true) {
            JOptionPane.showMessageDialog(this, "采购入库成功");
            //更新商品表
            btnSearchActionPerformed(evt);//调用查询方法
        } else {
            JOptionPane.showMessageDialog(this, "采购入库失败");
        }
        //清空采购表
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
    }//GEN-LAST:event_btnPurInActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        FrameUtil.framemap.remove(PurInFrame.class.getName());
    }//GEN-LAST:event_formInternalFrameClosed

    private void tblPurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPurchaseMouseClicked
        // 选中某行
        selectedRow = this.tblPurchase.getSelectedRow();
    }//GEN-LAST:event_tblPurchaseMouseClicked
    private void addPurchaseTable(Vector vt) {
        boolean flag = false;
        DefaultTableModel dtm = (DefaultTableModel) this.tblPurchase.getModel();
        for (int i = 0; i < dtm.getRowCount(); i++) {
            if (vt.get(0) == tblPurchase.getValueAt(i, 0)) {
                flag = true;
                break;
            }
        }
        if (flag == false) {
            dtm.addRow(vt);
        }
    }

    private void showOnProductTable(List<Product> list) {
        // 1. 获取表格(tblProduct)模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblProduct.getModel();
        // 2. 清空表格信息
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        // 3.显示数据
        for (Product p : list) {
            Vector vt = new Vector();
            vt.add(p.getProid());
            vt.add(p.getProname());
            vt.add(p.getType());
            vt.add(p.getColor());
            vt.add(p.getSugpurchase());
            vt.add(p.getSafecount());
            vt.add(p.getNowcount());
            dtm.addRow(vt);
        }

    }

    public void initPurchaseTable() {
        JComboBox cobsup = new JComboBox();
        List<Supplier> suplist = supbiz.findAll();
        for (Supplier sup : suplist) {
            cobsup.addItem(sup);
        }
        this.tblPurchase.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(cobsup));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPurIn;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTable tblPurchase;
    private javax.swing.JTextField txtCondition;
    // End of variables declaration//GEN-END:variables
}
