/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ouc.cpss.view;

import com.ouc.cpss.biz.PurchaseBiz;
import com.ouc.cpss.biz.PurchaseBizImpl;
import com.ouc.cpss.biz.SupplierBiz;
import com.ouc.cpss.biz.SupplierBizImpl;
import com.ouc.cpss.po.Purchase;
import com.ouc.cpss.po.Supplier;
import com.ouc.cpss.util.LocationUtil;
import com.ouc.cpss.vo.ViewPurchase;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author su
 */
public class PurReturnFrame extends javax.swing.JInternalFrame {

    PurchaseBiz pbiz = new PurchaseBizImpl();
    SupplierBiz supbiz = new SupplierBizImpl();

    int selectrow = -1;// 确保退货时选中了采购单

    /**
     * Creates new form PurReturn
     */
    public PurReturnFrame() {
        initComponents();
        LocationUtil.setScreenCenter(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        purPicPane1 = new com.ouc.cpss.view.PurPicPane();
        jLabel1 = new javax.swing.JLabel();
        txtCondition = new javax.swing.JTextField();
        btnQuery = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPurchase = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPurid = new javax.swing.JTextField();
        txtProid = new javax.swing.JTextField();
        txtPurcount = new javax.swing.JTextField();
        txtReturnAmount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnPurReturn = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        dateEnd = new com.ouc.cpss.util.DateChooserJButton();
        dateStart = new com.ouc.cpss.util.DateChooserJButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("采购退货");

        purPicPane1.setPreferredSize(new java.awt.Dimension(793, 470));

        jLabel1.setText("--");

        btnQuery.setText("查询");
        btnQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryActionPerformed(evt);
            }
        });

        jLabel2.setText("采购信息");

        tblPurchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "采购编号", "商品编号", "商品名称", "商品型号", "当前库存", "供应商名称", "采购数量", "采购单价", "采购时间"
            }
        ));
        tblPurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPurchaseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPurchase);

        jLabel3.setText("采购编号");

        jLabel4.setText("商品编号");

        jLabel5.setText("采购数量");

        txtPurid.setEditable(false);

        txtProid.setEditable(false);

        txtPurcount.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtPurid, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtProid, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtPurcount, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtPurid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPurcount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jLabel6.setText("退货数量");

        btnPurReturn.setText("确认退货");
        btnPurReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurReturnActionPerformed(evt);
            }
        });

        btnCancel.setText("取消");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        dateEnd.setPreferredSize(new java.awt.Dimension(80, 22));

        dateStart.setPreferredSize(new java.awt.Dimension(80, 22));

        javax.swing.GroupLayout purPicPane1Layout = new javax.swing.GroupLayout(purPicPane1);
        purPicPane1.setLayout(purPicPane1Layout);
        purPicPane1Layout.setHorizontalGroup(
            purPicPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, purPicPane1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(purPicPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, purPicPane1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtReturnAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnPurReturn)
                        .addGap(60, 60, 60)
                        .addComponent(btnCancel)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, purPicPane1Layout.createSequentialGroup()
                        .addGroup(purPicPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(purPicPane1Layout.createSequentialGroup()
                                .addComponent(dateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnQuery)))
                        .addGap(30, 30, 30))))
            .addGroup(purPicPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(purPicPane1Layout.createSequentialGroup()
                    .addGroup(purPicPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(purPicPane1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2))
                        .addGroup(purPicPane1Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(29, Short.MAX_VALUE)))
        );
        purPicPane1Layout.setVerticalGroup(
            purPicPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purPicPane1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(purPicPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuery)
                    .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(dateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(purPicPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtReturnAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPurReturn)
                    .addComponent(btnCancel))
                .addGap(28, 28, 28))
            .addGroup(purPicPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(purPicPane1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(136, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(purPicPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(purPicPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryActionPerformed
        //按条件查询采购单
        //1获取条件
        String start = this.dateStart.getText();
        String end = this.dateEnd.getText();
        String conditions = this.txtCondition.getText().trim();
        //调用业务
        List<ViewPurchase> list = pbiz.findByCondition(start, end, conditions);
        //显示在表格中
        showOnTable(list);

    }//GEN-LAST:event_btnQueryActionPerformed

    private void tblPurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPurchaseMouseClicked
        selectrow = this.tblPurchase.getSelectedRow();//selectrow为类属性
        Integer purid = (Integer) this.tblPurchase.getValueAt(selectrow, 0);
        Integer pid = (Integer) this.tblPurchase.getValueAt(selectrow, 1);
        Integer purchaseamount = (Integer) this.tblPurchase.getValueAt(selectrow, 6);
        //显示在文本框
        this.txtPurid.setText(purid.toString());
        this.txtProid.setText(pid.toString());
        this.txtPurcount.setText(purchaseamount.toString());

    }//GEN-LAST:event_tblPurchaseMouseClicked

    private void btnPurReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurReturnActionPerformed
        // TODO add your handling code here:
        if (selectrow == -1) {
            JOptionPane.showMessageDialog(this, "请选择要退货的采购单信息");
            return;
        }

        //获取退货信息
        Integer purid = Integer.parseInt(this.txtPurid.getText());
        Integer proid = Integer.parseInt(this.txtProid.getText());
        Integer purcount = Integer.parseInt(this.txtPurcount.getText());
        Supplier sup = supbiz.findBySubQuery(purid);
        int supid = sup.getSupid();
        BigDecimal prtprice = new BigDecimal(this.tblPurchase.getValueAt(selectrow, 7).toString());
        //获取退货数量
        String sreturnAmount = this.txtReturnAmount.getText();
        //数据验证
        String regex = "[1-9][0-9]*";
        if (sreturnAmount.matches(regex) == false) {
            JOptionPane.showMessageDialog(this, "请填写整数");
            return;
        }
        // 转换退货数量
        Integer prtcount = Integer.parseInt(sreturnAmount);
        // 判断是否超过采购数量
        if (prtcount > purcount) {
            JOptionPane.showMessageDialog(this, "退货数量大于采购数量");
            return;
        }
        // 获取退货总金额
       // BigDecimal prttotal = new BigDecimal(prtprice.multiply(new BigDecimal(prtcount)).toString());
        // 调用业务
        java.sql.Date prtdate = new java.sql.Date(new java.util.Date().getTime());

        boolean result = pbiz.purchasereturn(proid, purid, supid, prtcount, prtprice, prtdate);
        if (result == true) {
            JOptionPane.showMessageDialog(this, "退货成功");
            btnQueryActionPerformed(evt);
        } else {
            JOptionPane.showMessageDialog(this, "退货失败");
        }
        //清空文本框
        this.txtProid.setText("");
        this.txtPurid.setText("");
        this.txtPurcount.setText("");
        this.txtReturnAmount.setText("");
        selectrow = -1;
    }//GEN-LAST:event_btnPurReturnActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        //清空文本框
        this.txtProid.setText("");
        this.txtPurid.setText("");
        this.txtPurcount.setText("");
        this.txtReturnAmount.setText("");
        selectrow = -1;
    }//GEN-LAST:event_btnCancelActionPerformed
    private void showOnTable(List<ViewPurchase> list) {
        //1 表格模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblPurchase.getModel();
        //2清空表格
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        //3 添加数据
        for (ViewPurchase pur : list) {
            Vector vt = new Vector();
            vt.add(pur.getPurid());
            vt.add(pur.getProid());
            vt.add(pur.getProname());
            vt.add(pur.getType());
            vt.add(pur.getNowcount());
            vt.add(pur.getSupname());
            vt.add(pur.getPurcount());
            vt.add(pur.getPurprice());
            vt.add(pur.getPurdate());
            dtm.addRow(vt);

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPurReturn;
    private javax.swing.JButton btnQuery;
    private com.ouc.cpss.util.DateChooserJButton dateEnd;
    private com.ouc.cpss.util.DateChooserJButton dateStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.ouc.cpss.view.PurPicPane purPicPane1;
    private javax.swing.JTable tblPurchase;
    private javax.swing.JTextField txtCondition;
    private javax.swing.JTextField txtProid;
    private javax.swing.JTextField txtPurcount;
    private javax.swing.JTextField txtPurid;
    private javax.swing.JTextField txtReturnAmount;
    // End of variables declaration//GEN-END:variables

}
